# Generated by Django 4.1.7 on 2023-03-13 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_catalog_products_customuser_avatar_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 10, 52, 43, 394606, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 10, 52, 43, 394606, tzinfo=datetime.timezone.utc)),
        ),
    ]
