# Generated by Django 4.2.3 on 2023-07-25 13:28

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_alter_catalog_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 13, 28, 22, 888170)),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 13, 28, 22, 888170)),
        ),
        migrations.RemoveField(
            model_name='projects',
            name='likes',
        ),
        migrations.AddField(
            model_name='projects',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
