# Generated by Django 4.1.7 on 2023-03-27 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_alter_catalog_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='preview',
        ),
        migrations.AddField(
            model_name='catalog',
            name='first_preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='catalog',
            name='second_preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='catalog',
            name='third_preview',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 9, 54, 6, 983096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 27, 9, 54, 6, 983096, tzinfo=datetime.timezone.utc)),
        ),
    ]
